---
- hosts: tag_Name_app
  user: ec2-user
  gather_facts: true
  become: yes
  vars:
    linux_distribution: "{{ ansible_distribution }}"
  vars_files:
    - ./variables.yml
  roles:
  - { role: "{{ role_name }}"
    }
